spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: zuul-server
server:
  port: 8889
  servlet:
    context-path: /
eureka:
  client:
    service-url:
      defaultZone: http://user:admin@127.0.0.1:8888/eureka
zuul:
  routes:
    authServer:
      path: /authToken/**
      #服务名称
      serviceId: auth-server
    daoServer:
      path: /doc/**
      #服务名称
      serviceId: dao-server
